Update build 21.yml

diff --git a/.github/workflows/build 21.yml b/.github/workflows/build 21.yml
--- a/.github/workflows/build 21.yml
+++ b/.github/workflows/build 21.yml
@@ -51,25 +51,23 @@ jobs:
           sed -i 's/CONFIG_TARGET_ROOTFS_PARTSIZE=.*/CONFIG_TARGET_ROOTFS_PARTSIZE=512/' .config || echo "CONFIG_TARGET_ROOTFS_PARTSIZE=512" >> .config
           
           # Paket x86 Lengkap (Driver LAN + PHP8 + Modem)
-          PACKAGES="-dnsmasq dnsmasq-full base-files ca-bundle dropbear e2fsprogs firewall4 fstools \
-          kmod-button-hotplug kmod-nft-offload libc libgcc libustream-mbedtls logd \
-          mkf2fs mtd netifd nftables odhcp6c odhcpd-ipv6only partx-utils ppp ppp-mod-pppoe procd-ujail \
-          uci uclient-fetch urandom-seed urngd luci luci-compat luci-lib-base kmod-usb-net-huawei-cdc-ncm \
-          kmod-usb-net kmod-usb-net-rndis luci-lib-ip luci-lib-jsonc luci-lib-nixio luci-mod-admin-full \
-          luci-mod-network kmod-usb-net-rtl8150 kmod-usb-net-rtl8152 kmod-usb-net-asix kmod-usb-net-asix-ax88179 \
-          kmod-mii luci-mod-status luci-mod-system luci-proto-3g luci-proto-mbim mbim-utils picocom minicom \
+          PACKAGES="PACKAGES="-dnsmasq dnsmasq-full base-files ca-bundle dropbear e2fsprogs firewall fstools \
+          kmod-button-hotplug libc libgcc libustream-mbedtls logd mkf2fs mtd netifd odhcp6c odhcpd-ipv6only \
+          partx-utils ppp ppp-mod-pppoe procd-ujail uci uclient-fetch urandom-seed urngd luci luci-compat \
+          luci-lib-base kmod-usb-net kmod-usb-net-asix kmod-usb-net-asix-ax88179 kmod-usb-net-rtl8150 \
+          kmod-usb-net-rtl8152 kmod-usb-net-huawei-cdc-ncm kmod-usb-net-rndis kmod-usb-net-cdc-mbim \
+          kmod-usb-net-cdc-ncm netdata vnstat2 vnstati2 php8-cli php8-fastcgi php8-fpm \
+          php8-mod-session php8-mod-ctype php8-mod-fileinfo php8-mod-zip php8-mod-iconv php8-mod-mbstring \
+          luci-lib-ip luci-lib-jsonc luci-lib-nixio luci-mod-admin-full luci-mod-network \
+          lluci-mod-status luci-mod-system luci-proto-3g luci-proto-mbim mbim-utils picocom minicom \
           luci-proto-ncm luci-proto-ppp luci-proto-qmi screen kmod-tun ttyd kmod-usb-atm kmod-macvlan \
-          kmod-usb-net-cdc-ncm kmod-usb-net-cdc-mbim luci-proto-modemmanager modemmanager modemmanager-rpcd \
-          libqmi libmbim glib2 ipset libcap libcap-bin ruby ruby-yaml kmod-inet-diag kmod-nft-tproxy \
-          ip-full php8 haproxy tcpdump UDPspeeder irqbalance kmod-dummy bc uhttpd uhttpd-mod-ubus unzip \
-          uqmi usb-modeswitch uuidgen zstd wwan ziptool zoneinfo-asia zoneinfo-core zram-swap bash kmod-r8169 kmod-r8101 \
-          openssh-sftp-server adb wget-ssl httping htop jq tar coreutils-sleep coreutils-stat nano fping \
-          kmod-nls-utf8 kmod-usb-storage cgi-io chattr comgt comgt-ncm coremark coreutils coreutils-base64 \
-          coreutils-nohup kmod-usb-net-sierrawireless kmod-usb-serial-qualcomm kmod-usb-serial-sierrawireless \
-          luci-app-ttyd luci-theme-material iw iwinfo wireless-regdb netdata vnstat2 vnstati2 \
-          php8-cli php8-fastcgi php8-fpm php8-mod-session php8-mod-ctype php8-mod-fileinfo php8-mod-zip php8-mod-iconv \
-          php8-mod-mbstring luci-theme-material wpad-basic-wolfssl iw iwinfo hostapd-common kmod-e1000e kmod-forcedeth \
-          kmod-ath10k ath10k-firmware-qca9377 ath10k-firmware-qca988x"
+          luci-proto-modemmanager modemmanager modemmanager-rpcd libqmi libmbim glib2 ipset libcap libcap-bin \
+          ruby ruby-yaml kmod-inet-diag ip-full php8 haproxy tcpdump UDPspeeder irqbalance bc \
+          uhttpd uhttpd-mod-ubus unzip uqmi usb-modeswitch uuidgen zstd wwan ziptool zoneinfo-asia \
+          zoneinfo-core zram-swap bash openssh-sftp-server adb wget-ssl httping htop jq tar \
+          coreutils-sleep coreutils-stat nano fping kmod-nls-utf8 kmod-usb-storage cgi-io chattr \
+          comgt comgt-ncm coremark coreutils coreutils-base64 coreutils-nohup \
+          kmod-usb-serial-qualcomm kmod-usb-serial-sierrawireless luci-app-ttyd luci-theme-material"
 
           # Eksekusi Build
           [ -d "${GITHUB_WORKSPACE}/files" ] && chmod -R +x "${GITHUB_WORKSPACE}/files/etc/uci-defaults"
@@ -78,12 +76,19 @@ jobs:
                      FILES="${{ github.workspace }}/file" \
                      V=s
           
-          # Kumpulkan Hasil (.img.gz dan .vmdk)
-          cp bin/targets/x86/64/*-generic-ext4-combined-efi.img.gz ${{ env.OUTPUT_DIR }}/
-          cp bin/targets/x86/64/*-combined-efi.vmdk ${{ env.OUTPUT_DIR }}/ 2>/dev/null || true
+      - name: Kumpulkan Hasil
+        run: |
+          RESULT_DIR="bin/targets/armvirt/64"
           
-          # Buat Tag untuk Release
-          echo "build_tag=x86_64_$(date +%Y%m%d_%H%M)" >> $GITHUB_ENV
+          if [ -d "$RESULT_DIR" ]; then
+            cp $RESULT_DIR/*.tar.gz ${{ env.OUTPUT_DIR }}/ 2>/dev/null || true
+            cp $RESULT_DIR/*.img.gz ${{ env.OUTPUT_DIR }}/ 2>/dev/null || true        
+            echo "Berhasil menyalin hasil build ke output directory."
+          else
+            echo "Error: Direktori hasil build tidak ditemukan!"
+            exit 1
+          fi       
+          echo "build_tag=S905X_OpenWrt_21.02_$(date +%Y%m%d_%H%M)" >> $GITHUB_ENV
 
       - name: Upload to GitHub Release
         uses: ncipollo/release-action@v1
@@ -94,7 +99,6 @@ jobs:
           makeLatest: true
           token: ${{ secrets.AKSI_TOKEN }}
           body: |
-            ## OpenWrt 25.12.1 x86_64
+            ## OpenWrt 21.02
             - **URL IB**: ${{ github.event.inputs.custom_url }}
             - **IP**: ${{ github.event.inputs.openwrt_ip }}
-            - **Files**: .img.gz (EFI Flashable) & .vmdk (VMware/Proxmox)
